-- AlterTable
ALTER TABLE "Adicional" ALTER COLUMN "id" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Sabor" ALTER COLUMN "id" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Cliente" ALTER COLUMN "id" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Pedido" ALTER COLUMN "id" SET DATA TYPE BIGINT;
ALTER TABLE "Pedido" ALTER COLUMN "clienteId" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "PedidoSabor" ALTER COLUMN "pedidoId" SET DATA TYPE BIGINT;
ALTER TABLE "PedidoSabor" ALTER COLUMN "saborId" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "PedidoAdicional" ALTER COLUMN "pedidoId" SET DATA TYPE BIGINT;
ALTER TABLE "PedidoAdicional" ALTER COLUMN "adicionalId" SET DATA TYPE BIGINT;
